### ISSUE TITLE
Some suggested features

### ISSUE THREAD

**Issue by xtk923** [brodyreeves/MyChatAlert#11]
This is my favorite addon in vanilla WOW. Thank you so much for creating it!

I have two suggested features:

1. Control panel access from chat channel. 

    It will be very convenient if we can open the control panel by-for example- `/wca`

2. Clickable reply as whisper.

    Is it possible to allow the users to click on the printed message on chat panel and start a whisper message to the respective person?

Again, thank you very much for creating this addon!

**Comment by brodyreeves** [comment]
Glad that you're liking it!
1. By control panel, do you mean the Interface/Options panel? Or the alert frame? Either way it's very easy to implement slash commands for both of those, and I'll get around to it soon
2. On the printed message, I don't believe there's a way I can do that without writing a whole chat-frame-replacement addon (which isn't really my aim with this). I can, however, make it so that the names in the alert frame are clickable for opening whispers, rather than the current select-for-copy that I have implemented. (I just found the api call to open the chat frame with a specified message, i.e. /w [name], and wasn't sure it was possible to do that)

**Comment by brodyreeves** [comment]
Closed issue because I moved the features requested into their own issues
