### ISSUE TITLE
[FEATURE adjustment] Tweak global channel to include filters

### ISSUE THREAD

**Issue by Myaukolka** [brodyreeves/MyChatAlert#33]
How does filter words feature supposed to work?
Does it has to skip keyword matched messages containing filtered word? If so this feature seems to not be working correctly.

If this feature has some other purpose please explain/add to readme what it does.

Advanced keywords with "+" and "-" are working just fine but it is redundant and not really intuitive to add *-filter* to each keyword.

**Comment by brodyreeves** [comment]
Words that you add to the filter list will be blacklisted from alerts. If a message is seen that matches a keyword and would normally trigger an alert, but contains a word in the filter list, then it won't trigger an alert. It seems to be working just fine for me, here's the way I tested it:  

0) First I disabled the player message filter so that I can trigger my own alerts (`core.lua:453`)
1) Add the `Say` channel as a channel to watch
2) Select the `Say` channel and add `test` as a keyword
3) Add `bad` as a filter word
4) If I say `test` in `/s` then I see an alert get triggered
5) If I say `test bad` in `/s` then I do not see an alert

I've been thinking of updating my README to be more comprehensive, so I'll work on that

**Comment by Myaukolka** [comment]
I've replicated your steps and it is indeed working with per channel settings.
However i was using **MyChatAlert Global Keywords** and trying to setup same keyword and filter in global lists results in `test bad` not being filtered out.

**Comment by brodyreeves** [comment]
Ah, I thought that was possibly the case. Currently that's the intended behavior 
('MyChatAlert Global **Keywords**' not being checked for filters). I was debating whether to change it to a 'MyChatAlert Gobal' channel and including filter checking there, and will probably go ahead and do that soon

I'm gonna rename this issue to relate to that more closely
